agentdid127/ResourcePackConverter

src/main/java/net/hypixel/resourcepack/impl/ChestConverter.java

Not sure if your open to pull requests but I was hoping to use the tool to convert some textures and found some inconsistencies ( between 1.14 and 1.15 converted ) which I have fixed

Fix chest converting.

---

.github/workflows/prerelease.yml
pom.xml

Update version control, change version number to a not used one

---

.github/workflows/prerelease.yml
.github/workflows/release.yml

fixes the fact that it doesn't auto-generate a jar with the new format

1.5.2-pre3 hotfix

---

.github/workflows/prerelease.yml
.github/workflows/release.yml

1.5.2-pre fix2

---

pom.xml
src/main/java/com/agentdid127/resourcepack/impl/forwards/PackMetaConverter.java

whoops, i guess 1.17b wasn't ready yet

---

conversions/Backwards/src/main/java/com/agentdid127/resourcepack/backwards/BackwardsPackConverter.java
conversions/Backwards/src/main/java/com/agentdid127/resourcepack/backwards/impl/BlockStateConverter.java
conversions/Backwards/src/main/java/com/agentdid127/resourcepack/backwards/impl/DeleteFileConverter.java
conversions/Backwards/src/main/java/com/agentdid127/resourcepack/backwards/impl/ModelConverter.java
conversions/Forwards/src/main/java/com/agentdid127/resourcepack/forwards/ForwardsPackConverter.java
conversions/Forwards/src/main/java/com/agentdid127/resourcepack/forwards/impl/AtlasConverter.java
conversions/Forwards/src/main/java/com/agentdid127/resourcepack/forwards/impl/BlockStateConverter.java
conversions/Forwards/src/main/java/com/agentdid127/resourcepack/forwards/impl/ModelConverter.java

Fixes #127 
This will make custom textures and models work in 1.19.3 Haven't tested it yet, hence the draft conversion

Initial Atlas Conversion

---

conversions/Forwards/src/main/java/com/agentdid127/resourcepack/forwards/ForwardsPackConverter.java
conversions/Forwards/src/main/java/com/agentdid127/resourcepack/forwards/impl/PackMetaConverter.java
library/src/main/java/com/agentdid127/resourcepack/library/pack/ZipPack.java

PackMetaConverter: Update, and add supported_formats for 1.20.2+ and add missing version ints

PackMetaConverter: Add missing versions & add supported_formats field

---

library/src/main/java/com/agentdid127/resourcepack/library/utilities/ImageConverter.java

ImageConverter: Fix Broken stuff like chests & possibly other stuff

ImageConverter: Fix Broken stuff like chests & possibly other stuff

---

conversions/Forwards/src/main/java/com/agentdid127/resourcepack/forwards/ForwardsPackConverter.java
conversions/Forwards/src/main/java/com/agentdid127/resourcepack/forwards/impl/textures/OffHandCreator.java
conversions/Forwards/src/main/resources/forwards/gui.json

Add OffHandCreator for packs < 1.9

Add OffHandCreator for packs < 1.9

---

conversions/Forwards/src/main/java/com/agentdid127/resourcepack/forwards/impl/BlockStateConverter.java

Fix issue with not pre-appending "block/" for converting from 1.8 to 1.9+
Also removed duplicate code, and cleaned it up.

BlockStateConverter: Fix issue & Cleanup

---

conversions/Forwards/src/main/java/com/agentdid127/resourcepack/forwards/ForwardsPackConverter.java
conversions/Forwards/src/main/java/com/agentdid127/resourcepack/forwards/impl/textures/SlidersCreator.java
conversions/Forwards/src/main/resources/forwards/gui.json
library/src/main/java/com/agentdid127/resourcepack/library/utilities/ImageConverter.java

Adds SlidersCreator, which creates the "slider.png" file in textures/gui/ for 1.19.4+ when converting from below.

Add SlidersCreator for packs < 1.19.4

---

conversions/Backwards/src/main/java/com/agentdid127/resourcepack/backwards/impl/PackMetaConverter.java
conversions/Forwards/src/main/java/com/agentdid127/resourcepack/forwards/impl/PackMetaConverter.java

Fix 1.20.3 MCMeta support

---

conversions/Forwards/src/main/java/com/agentdid127/resourcepack/forwards/impl/textures/WaterConverter.java

Attempts to fix #183 , by halfing the output size of the water converter. Will need to be tested and verified.

attempt to fix water issue, as it seems to be doubled in size

---

library/src/main/java/com/agentdid127/resourcepack/library/utilities/ImageConverter.java

Fixes #196 which caused the grayscale method to strip all alpha/transparency from the image.

Fixes Grayscale Alpha Conversion

---

library/src/main/java/com/agentdid127/resourcepack/library/utilities/ImageConverter.java

Don't make values less than one round to one if not zero, when getting image multiplier

---

conversions/Forwards/src/main/resources/forwards/gui.json

Added forgotten "absorbing_full" and "absorbing_half" slicing in gui hearts.

Fixed Absorbing Hearts Slicing

---

conversions/Backwards/src/main/java/com/agentdid127/resourcepack/backwards/impl/PackMetaConverter.java
conversions/Forwards/src/main/java/com/agentdid127/resourcepack/forwards/impl/PackMetaConverter.java

let mcmeta support 1.20.5+

---

Applications/Console/src/main/java/com/agentdid127/resourcepack/Options.java
Applications/Gui/src/main/java/com/agentdid127/resourcepack/GUI.java
conversions/Backwards/src/main/java/com/agentdid127/resourcepack/backwards/BackwardsPackConverter.java
conversions/Backwards/src/main/java/com/agentdid127/resourcepack/backwards/impl/BlockStateConverter.java
conversions/Backwards/src/main/java/com/agentdid127/resourcepack/backwards/impl/LangConverter.java
conversions/Backwards/src/main/java/com/agentdid127/resourcepack/backwards/impl/MCPatcherConverter.java
conversions/Backwards/src/main/java/com/agentdid127/resourcepack/backwards/impl/ModelConverter.java
conversions/Backwards/src/main/java/com/agentdid127/resourcepack/backwards/impl/NameConverter.java
conversions/Backwards/src/main/java/com/agentdid127/resourcepack/backwards/impl/textures/MapIconConverter.java
conversions/Forwards/src/main/java/com/agentdid127/resourcepack/forwards/ForwardsPackConverter.java
conversions/Forwards/src/main/java/com/agentdid127/resourcepack/forwards/impl/AnimationConverter.java
conversions/Forwards/src/main/java/com/agentdid127/resourcepack/forwards/impl/BlockStateConverter.java
conversions/Forwards/src/main/java/com/agentdid127/resourcepack/forwards/impl/LangConverter.java
conversions/Forwards/src/main/java/com/agentdid127/resourcepack/forwards/impl/MCPatcherConverter.java
conversions/Forwards/src/main/java/com/agentdid127/resourcepack/forwards/impl/ModelConverter.java
conversions/Forwards/src/main/java/com/agentdid127/resourcepack/forwards/impl/NameConverter.java
conversions/Forwards/src/main/java/com/agentdid127/resourcepack/forwards/impl/SoundsConverter.java
conversions/Forwards/src/main/java/com/agentdid127/resourcepack/forwards/impl/SpacesConverter.java
conversions/Forwards/src/main/java/com/agentdid127/resourcepack/forwards/impl/textures/MapIconConverter.java
conversions/Forwards/src/main/java/com/agentdid127/resourcepack/forwards/impl/textures/ParticleTextureConverter.java
conversions/Forwards/src/main/java/com/agentdid127/resourcepack/forwards/impl/textures/slicing/Slicer.java
library/src/main/java/com/agentdid127/resourcepack/library/PackConverter.java
library/src/main/java/com/agentdid127/resourcepack/library/pack/Pack.java
library/src/main/java/com/agentdid127/resourcepack/library/pack/ZipPack.java
library/src/main/java/com/agentdid127/resourcepack/library/utilities/FileUtil.java
library/src/main/java/com/agentdid127/resourcepack/library/utilities/ImageConverter.java
library/src/main/java/com/agentdid127/resourcepack/library/utilities/JsonUtil.java
library/src/main/java/com/agentdid127/resourcepack/library/utilities/Logger.java

Here, I reworked the debug section, and fixes a few bugs.
Fixed #216
Fixed #227

Worksession from stream on 11/9/2024

---

conversions/Forwards/src/main/java/com/agentdid127/resourcepack/forwards/impl/NameConverter.java
conversions/Forwards/src/main/java/com/agentdid127/resourcepack/forwards/impl/textures/slicing/Slicer.java
library/src/main/java/com/agentdid127/resourcepack/library/utilities/FileUtil.java

Cleans up some stuff, fixes few issues I had when converting, should also fix #235

Small cleanup + fixes

---

conversions/Backwards/src/main/java/com/agentdid127/resourcepack/backwards/impl/EnchantPathConverter.java
conversions/Backwards/src/main/java/com/agentdid127/resourcepack/backwards/impl/NameConverter.java
conversions/Forwards/src/main/java/com/agentdid127/resourcepack/forwards/impl/NameConverter.java
library/src/main/java/com/agentdid127/resourcepack/library/utilities/Logger.java

Fixes #237
Tons of syntax cleanup and code modernization to match the forwards converter.

Fix a few bugs in Backwards conversion
